project:
  type: website
  output-dir: _site

website:
  title: "August Academy"

  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: projects.qmd
        text: Projects

      - href: about.qmd
        text: About

    right:
      - icon: github
        href: https://github.com/karthik-palaniappan

format:
  html:
    theme: cosmo
    css: styles.scss
    toc: true

execute:
  freeze: auto