project:
  type: website
  output-dir: docs

website:
  title: "Scientific Computing Lab | August Academy"
  site-url: "https://karthik-palaniappan.github.io"
  favicon: assets/favicon/AU-favicon.png

  navbar:
    logo: assets/logo/AugustAcademy-logo.png
    logo-alt: "August Academy"

    left:
      - href: research.qmd
        text: Research

      - href: about.qmd
        text: About

    right:
      - icon: github
        href: https://github.com/karthik-palaniappan
        aria-label: GitHub

      - icon: linkedin
        href: https://www.linkedin.com/in/karthikpalaniappan/
        aria-label: LinkedIn

  search:
    location: navbar
    type: textbox

  page-footer:
    left: |
      © 2026 August Academy · Scientific Computing Lab

    right: |
      [GitHub](https://github.com/karthik-palaniappan) ·
      [LinkedIn](https://www.linkedin.com/in/karthikpalaniappan/)

format:
  html:
    theme:
      - default
      - styles.scss

    toc: false
    smooth-scroll: true
    anchor-sections: true

execute:
  freeze: auto
